title: Ayush Verma # your name (or website title) here
logo: "/images/ayush.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Reach out to me: ayush.k1998@gmail.com, ayushv34_scs@jnu.ac.in
  <br>
  <a href="https://www.linkedin.com/in/ayushexploring/">LinkedIn</a>
  <br>
  <a href="https://scholar.google.com/citations?user=mldR9EoAAAAJ&hl=en&oi=sra">Google Scholar</a>
  <br>
  <a href="https://orcid.org/0000-0001-7249-1011">ORCiD</a>

  
theme: jekyll-theme-slate
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
